name: Acceptance Test

on:
  workflow_call:

jobs:
  acceptance-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Images
        uses: actions/cache@v4
        with:
          path: /tmp/images
          key: ${{ runner.os }}-images-${{ github.run_id }}-${{ github.run_number }}
      - name: Restore images
        run: |
          docker load -i /tmp/images/s3-antivirus.tar
      - name: Run Acceptance Tests
        run: make acceptance-test
