name: Code Quality Tests

on:
  workflow_call:

jobs:
  code-test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      - name: Run linting
        run: make lint
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3.28.13
        if: always()
        with:
          sarif_file: test-results/golangci-lint.sarif
      - name: Set up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: 1.19
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3.28.13
        with:
          languages: go
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3.28.13
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3.28.13
