name: Create Tags

on:
  workflow_call:
    outputs:
      tag:
        description: "Semver Tag"
        value: ${{ steps.bump_version.outputs.tag }}

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: |
          if [ "${{ github.head_ref }}" == "" ]; then
            echo BRANCH_NAME=main >> $GITHUB_ENV
          else
            echo BRANCH_NAME=${{ github.head_ref }} >> $GITHUB_ENV
          fi
        id: extract_branch
      - name: Bump version
        id: bump_version
        uses: anothrNick/github-tag-action@1.69.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          PRERELEASE: true
          PRERELEASE_SUFFIX: ${{ env.BRANCH_NAME }}
          RELEASE_BRANCHES: main
          WITH_V: true
    outputs:
      tag: ${{ steps.bump_version.outputs.tag }}
