name: Build Lambda Function and Layer Zips

on:
  workflow_call:

jobs:
  zip-lambda-build:
    name: "Build Lambda Zip"
    runs-on: ubuntu-latest
    # needs: ['build', 'unit-test', 'code-test', 'acceptance-test']
    # if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Lambda Package - Zip Build
        run: |
          make lambda-zip-build
        id: lambda-zip-build
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: myFunction
          path: build/myFunction.zip
      - name: Cleanup
        run: |
          make lambda-zip-clear

  build-lambda-layer-zip:
    name: "Build Lambda Layer Zip"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Layer Package - Zip Build
        run: |
          make layer-zip-build
        id: layer-zip-build
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: lambda_layer
          path: build/lambda_layer.zip
      - name: Test layer
        run: |
          make layer-zip-test
      - name: Cleanup
        run: |
          make layer-zip-clear
